import React from "react";
import Head from "next/head";
import { Box, Container, Flex, Text } from "@chakra-ui/react";

const DashboardPage: React.FC = () => {
  return (
    <>
      <Head>
        <title>hospe dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container overflowY="auto" maxW="4xl">
        <Flex
          direction={{ base: "column", md: "row" }}
          w="100%"
          justify="center"
          alignItems="center"
        >
          <Box w={{ base: "100%", md: "50%" }} pr="7px" backgroundColor="red">
            <Text>Left Column</Text>
          </Box>
          <Box w={{ base: "100%", md: "50%" }} pr="7px" backgroundColor="blue">
            <Text>Right Column</Text>
          </Box>
        </Flex>
      </Container>
    </>
  );
};

export default DashboardPage;
