import { Button } from "@chakra-ui/button";
import { FormControl, FormLabel } from "@chakra-ui/form-control";
import { Input } from "@chakra-ui/input";
import {
  Box,
  Container,
  Flex,
  Text,
} from "@chakra-ui/react";
import { Select } from "@chakra-ui/select";
import Head from "next/head";
import React from "react";
import OldCard from "../components/laboratory/previous-test-card";

const Laboratory: React.FC = () => {
  //temporary data for fill appointment date list
  const today = new Date();

  return (
    <>
      <Head>
        <title>Laboratory Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container overflowY="auto" maxW="6xl" mt="1px">
        <Flex direction={{ base: "column", md: "row" }} w="100%" mt="5px">
          <Flex direction="column" w={{ base: "100%", md: "70%" }}>
            {/* Searching space */}
            <Box
              w="100%"
              mr={5}
              pr="60px"
              backgroundColor="white"
              height="200px"
            >
              <Text fontSize="24px" mx="10px" mb="30px" textColor="#777A79">
                New Appoinment
              </Text>

              <form>
                {/* Select test type */}
                <FormControl id="test_type">
                  <Flex
                    direction={{ base: "column", md: "row" }}
                    align={{ base: "left", md: "center" }}
                  >
                    <Flex w="45%">
                      <FormLabel
                        htmlFor="name"
                        color="Background.text"
                        mx="10px"
                        fontSize="18px"
                      >
                        Test Type
                      </FormLabel>
                    </Flex>

                    <Flex w={{ base: "auto", md: "450px" }}>
                      <Select
                        placeholder="Select Test Type"
                        bg="brand.background"
                      >
                        <option value="option1">Test 1</option>
                        <option value="option2">Test 2</option>
                        <option value="option3">Test 3</option>
                      </Select>
                    </Flex>
                  </Flex>
                </FormControl>

                {/* Select Date */}
                <FormControl id="speciality" mt="25px">
                  <Flex
                    direction={{ base: "column", md: "row" }}
                    align={{ base: "left", md: "center" }}
                  >
                    <Flex w="45%">
                      <FormLabel
                        htmlFor="speciality"
                        color="Background.text"
                        mx="10px"
                        fontSize="18px"
                      >
                        Date
                      </FormLabel>
                    </Flex>

                    <Flex w={{ base: "auto", md: "450px" }}>
                      <Input type="Date" bg="brand.background" border="none" />
                    </Flex>
                  </Flex>
                </FormControl>

                <Flex justify={{ base: "flex-start", md: "flex-end" }}>
                  <Button
                    type="submit"
                    bg="brand.secondry"
                    mt="25px"
                    w="120px"
                    fontSize="18px"
                    textColor="white"
                    borderRadius="12px"
                  >
                    Schedule
                  </Button>
                </Flex>
              </form>
            </Box>

            {/* Previous laboratory requests space */}
            <Text
              fontSize="24px"
              mt={{ base: "160px", md: "70px" }}
              mx="10px"
              mb="30px"
              textColor="#777A79"
            >
              Previous Laboratory Requests
            </Text>

            <Box
              w="100%"
              pr="60px"
              backgroundColor="white"
              height="max-content"
              mt={4}
    
            >
              <OldCard
                type="FBC"
                day={today.getUTCDay()}
                month={today.getMonth()}
                yr={today.getUTCFullYear()}
                status="Complete"
              ></OldCard>

              <OldCard
                type="Culture"
                day={today.getUTCDay()}
                month={today.getMonth()}
                yr={today.getUTCFullYear()}
                status="Pending"
              ></OldCard>
            </Box>

            {/*Horizontal Advertisment Space  */}
            <Box
              w="100%"
              pr="7px"
              backgroundColor="brand.background"
              height="200px"
              mt={5}
              display={{ base: "block", md: "none" }}
            ></Box>
          </Flex>

          {/* Vertical Adverteisment Space */}
          <Flex w="50%" display={{ base: "none", md: "inline-flex" }} mx="20px">
            <Box
              w="100%"
              pr="7px"
              backgroundColor="brand.background"
              height="100vh"
              ml={4}
            ></Box>
          </Flex>
        </Flex>
        <Flex></Flex>
      </Container>
    </>
  );
};

export default Laboratory;
