import React from "react";
import {
  Box,
  Button,
  Container,
  Flex,
  FormControl,
  FormLabel,
  Input,
  SimpleGrid,
} from "@chakra-ui/react";
import Head from "next/head";
import ResultCard from "../components/search/result-card";

const Search: React.FC = ({}) => {
  return (
    <>
      <Head>
        <title>Search Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container overflowY="auto" maxW="6xl" mt="1px">
        <Flex direction={{ base: "column", md: "row" }} w="100%" mt="5px">
          <Flex direction="column" w={{ base: "100%", md: "70%" }}>
            {/* Searching space */}
            <Box
              w="100%"
              mr={5}
              pr="60px"
              backgroundColor="white"
              height="200px"
            >
              <form>
                {/* Search by name */}
                <FormControl id="name">
                  <Flex
                    direction={{ base: "column", md: "row" }}
                    align={{ base: "left", md: "center" }}
                  >
                    <Flex w="45%">
                      <FormLabel
                        htmlFor="name"
                        color="Background.text"
                        mx="10px"
                      >
                        Search by name
                      </FormLabel>
                    </Flex>

                    <Flex  w={{base:"auto", md:"450px"}}>
                      <Input type="text" bg="brand.background" border="none" />
                    </Flex>
                  </Flex>
                </FormControl>

                {/* Search by speciality */}
                <FormControl id="speciality" mt="25px">
                  <Flex
                    direction={{ base: "column", md: "row" }}
                    align={{ base: "left", md: "center" }}
                  >
                    <Flex w="45%">
                      <FormLabel
                        htmlFor="speciality"
                        color="Background.text"
                        mx="10px"
                      >
                        Speciality
                      </FormLabel>
                    </Flex>

                    <Flex w={{base:"auto", md:"450px"}}>
                      <Input type="text" bg="brand.background" border="none" />
                    </Flex>
                  </Flex>
                </FormControl>

                <Flex justify={{base:"flex-start", md:"flex-end"}}>
                  <Button
                    type="submit"
                    bg="brand.secondry"
                    mt="25px"
                    w="120px"
                    fontSize="18px"
                    textColor="white"
                    borderRadius="12px"
                   >
                    Search
                  </Button>
                </Flex>
              </form>
            </Box>

            {/*Horizontal Advertisment Space  */}
            <Box
              w="100%"
              pr="7px"
              backgroundColor="brand.background"
              height="200px"
              mt={20}
              display={{ base: "block", md: "none" }}
            ></Box>

            {/* Search result space */}
            <Box
              w="100%"
              pr="60px"
              mx={10}
              backgroundColor="white"
              height="400px"
              mt={4}
            >
              <SimpleGrid columns={2} spacing="12px" mb="50px">
                <ResultCard name="John Smith" type="Surgon" hospital="Asiri Hospital"></ResultCard>
                <ResultCard name="DJ Bravo" type="VP" hospital="Asiri Hospital"></ResultCard>
                <ResultCard name="David Warner" type="Dentiest" hospital="Asiri Hospital"></ResultCard>
                <ResultCard name="David Malan" type="VOG" hospital="Asiri Hospital"></ResultCard>
              </SimpleGrid>
            </Box>
          </Flex>

          {/* Vertical Adverteisment Space */}
          <Flex w="50%"  display={{ base: "none", md: "inline-flex" }} mx="20px">
            <Box
              w="100%"
              pr="7px"
              backgroundColor="brand.background"
              height="100vh"
              ml={4}              
            ></Box>
          </Flex>
        </Flex>
        <Flex></Flex>
      </Container>
    </>
  );
};

export default Search;
